project:
  type: website
  output-dir: docs

website:
  title: "Quantitative Pharmacology and Systems Modeling Lab"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: research.html
        text: Research
      - href: publications.html
        text: Publications
      - href: team.html
        text: Team
      - href: opportunities.html
        text: Opportunities
      - href: contact.html
        text: Contact
    right:
      - icon: github
        href: https://github.com/javiera-cortes-rios
      - icon: linkedin
        href: https://www.linkedin.com/in/cortesriosj/
      - icon: envelope
        href: mailto:jacortes4@uc.cl
  page-footer:
    left: "© Javiera Cortés"
    right: "Quantitative Pharmacology and Systems Modeling Lab"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
